# Generated by Django 4.1.7 on 2023-02-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "year_of_manufacture",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("main_category", models.CharField(max_length=100)),
                ("detailed_classification", models.CharField(max_length=100)),
                ("serving_size", models.PositiveIntegerField()),
                (
                    "serving_unit",
                    models.CharField(choices=[("g", "g"), ("ml", "ml")], max_length=2),
                ),
                ("total_contents", models.PositiveIntegerField(blank=True, null=True)),
                ("total_calories", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("total_sugars", models.FloatField(blank=True, null=True)),
                ("sodium", models.FloatField(blank=True, null=True)),
                ("cholesterol", models.FloatField(blank=True, null=True)),
                ("saturated_fatty_acids", models.FloatField(blank=True, null=True)),
                ("trans_fatty_acids", models.FloatField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.category"
                    ),
                ),
            ],
        ),
    ]
