# Generated by Django 4.1.7 on 2023-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_foodlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(
                default="default_food.jpg", upload_to="food_images"
            ),
        ),
    ]
