# Generated by Django 4.1.7 on 2023-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_food_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="serving_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
