# Generated by Django 4.1.7 on 2023-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member", old_name="is_admin", new_name="is_staff",
        ),
        migrations.AlterField(
            model_name="member",
            name="activity_level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="member", name="name", field=models.CharField(max_length=30),
        ),
    ]
